DROP DATABASE IF EXISTS danielle_DB;
CREATE DATABASE danielle_DB;

CREATE TABLE user (
  id INTEGER(11) AUTO_INCREMENT NOT NULL,
  username VARCHAR(100) NOT NULL,
  pass VARCHAR(100) NOT NULL,
  orderID INT NULL
)


