---- Admin Login ----
INSERT INTO users (username, password) VALUES ("admin", "password");

---- Items (All) ----
USE danielle_DB;
INSERT INTO items (itemName, itemCategory, itemDesc, itemPrice, itemImg) VALUES ("O.G. Chocolate Chip", "Cookies", "The original favorite made with a browned butter base, milk chocolate, dark chocolate, topped a sprinkle of flaked salt for savoriness.", 3.00, "https://hosting.photobucket.com/images/i/danielle-m-estrella/IMG_20201029_090329_731.jpg?width=590&height=370&fit=bounds");
INSERT INTO items (itemName, itemCategory, itemDesc, itemPrice, itemImg) VALUES ("Nutella Stuffed", "Cookies", "If Ferro Roschette could be a cookie, this would be it. A delicious treat with roasted hazelnuts and a creamy Nutella center.", 3.00, "https://hosting.photobucket.com/images/i/danielle-m-estrella/20210227_130831_2(1).jpg?width=590&height=370&fit=bounds");
INSERT INTO items (itemName, itemCategory, itemDesc, itemPrice, itemImg) VALUES ("Roasted Peanut Toffee", "Cookies", "A cookie with deliciously roasted peanuts, roasted black sesame seeds, toffee, and of course peanut butter.", 3.00, "https://hosting.photobucket.com/images/i/danielle-m-estrella/04D82A60-DA8E-4FC0-9EAD-CA1BB59A4F65.jpeg?width=590&height=370&fit=bounds");
INSERT INTO items (itemName, itemCategory, itemDesc, itemPrice, itemImg) VALUES ("Chocolate Ginger Molasses", "Cookies", "Wait, did you say ginger? Yes, we did. This vegan delite is made with freshly grated ginger, milk chocolate, and warming spices.", 3.00, "https://hosting.photobucket.com/images/i/danielle-m-estrella/2ED277B7-F74B-4B8C-A1A8-81EB19E77B67.jpeg?width=590&height=370&fit=bounds");
 
INSERT INTO items (itemName, itemCategory, itemDesc, itemPrice, itemImg) VALUES ("Choco-Nut", "Cookies", "A vegan take on the chocolate chip cookie made with both macerated and toasted coconut, dark and milk chocolate that is finished with flaked salt.", 3.00, "https://hosting.photobucket.com/images/i/danielle-m-estrella/7E099689-0233-45E1-9BF2-C5961E63F44E.jpeg?width=590&height=370&fit=bounds");
INSERT INTO items (itemName, itemCategory, itemDesc, itemPrice, itemImg) VALUES ("Lemon Hibiscus", "Cookies", "A new vegan experiment comprises of a condensed hibiscus simple syrup (made in house), fresh lemon juice, and white chocolate chips.", 3.00, "https://hosting.photobucket.com/images/i/danielle-m-estrella/(edited)_1B43E007-F532-4BD8-A00D-95FBD6F9A2E8.jpeg?width=590&height=370&fit=bounds");
INSERT INTO items (itemName, itemCategory, itemDesc, itemPrice, itemImg) VALUES ("Mini Lemon Cake", "Cakes", "Not your ordinary lemon cake. This little treat is topped with citrus cream cheese vanilla bean swiss meringue buttercream, manderin curd,meyer-lemon curd, and finally garnished with gold flake.", 8.00, "https://hosting.photobucket.com/images/i/danielle-m-estrella/F149C15D-C872-473C-B3C4-0E9017B1C9E2.jpeg?width=590&height=370&fit=bounds");
 
INSERT INTO items (itemName, itemCategory, itemDesc, itemPrice, itemImg) VALUES ("Mini Blood Orange Cake", "Cakes", "Really delicious cake that I can't wait to eat.", 11.00, "https://via.placeholder.com/300x400/FFFFFF/000000/?text=Cakes");
INSERT INTO items (itemName, itemCategory, itemDesc, itemPrice, itemImg) VALUES ("Mini Roasted Hazelnut Cake", "Cakes", "A beautifully decorate mini cake with roasted hazelnut, browned butter buttercream, swiss meringue buttercream, salted caramel, and topped with coconut ganache.", 11.00, "https://hosting.photobucket.com/images/i/danielle-m-estrella/(edited)_7725E735-1185-4977-AD93-859CDDA3E991.jpeg?width=590&height=370&fit=bounds");
INSERT INTO items (itemName, itemCategory, itemDesc, itemPrice, itemImg) VALUES ("Mini Chocolate Cake", "Cakes", "Really delicious cake that I can't wait to eat.", 8.00, "https://via.placeholder.com/300x400/FFFFFF/000000/?text=Cakes");
INSERT INTO items (itemName, itemCategory, itemDesc, itemPrice, itemImg) VALUES ("Calamansi Tart", "Special_Treats", "The Danielle Signare Pastry. Like a sweeter-lemon crossed with a kumquat, Colamansi is a Philipine citrus fruit we use to make the pastry curd filling, that sits in a brown and black sesame pastry tart, black sesame praline, topped with lightly torched meringue.", 8.00, "https://hosting.photobucket.com/images/i/danielle-m-estrella/7325480F-D0D6-4A86-846F-9CBC8030D65D.jpeg?width=590&height=370&fit=bounds");
INSERT INTO items (itemName, itemCategory, itemDesc, itemPrice, itemImg) VALUES ("Calamansi Tart", "Special_Treats", "The Danielle Signare Pastry. Like a sweeter-lemon crossed with a kumquat, Colamansi is a Philipine citrus fruit we use to make the pastry curd filling, that sits in a brown and black sesame pastry tart, black sesame praline, topped with lightly torched meringue.", 8.00, "https://hosting.photobucket.com/images/i/danielle-m-estrella/20210303_091025.jpg?width=590&height=370&fit=bounds");
INSERT INTO items (itemName, itemCategory, itemDesc, itemPrice, itemImg) VALUES ("Calamansi Tart", "Special_Treats", "The Danielle Signare Pastry. Like a sweeter-lemon crossed with a kumquat, Colamansi is a Philipine citrus fruit we use to make the pastry curd filling, that sits in a brown and black sesame pastry tart, black sesame praline, topped with lightly torched meringue.", 8.00, "https://hosting.photobucket.com/images/i/danielle-m-estrella/7325480F-D0D6-4A86-846F-9CBC8030D65D.jpeg?width=590&height=370&fit=bounds");
INSERT INTO items (itemName, itemCategory, itemDesc, itemPrice, itemImg) VALUES ("Calamansi Tart", "Special_Treats", "The Danielle Signare Pastry. Like a sweeter-lemon crossed with a kumquat, Colamansi is a Philipine citrus fruit we use to make the pastry curd filling, that sits in a brown and black sesame pastry tart, black sesame praline, topped with lightly torched meringue.", 8.00, "https://hosting.photobucket.com/images/i/danielle-m-estrella/20210303_091025.jpg?width=590&height=370&fit=bounds");





